//Crie um programa que leia um número qualquer e mostre na tela a sua tabuada
const prompt = require('prompt-sync')()
let nmr = Number(prompt("Digite um número: "))
console.log(`Tabuada do ${nmr}: `)
console.log(`${nmr} x 1 = ${nmr *1}`)
console.log(`${nmr} x 2 = ${nmr *2}`)
console.log(`${nmr} x 3 = ${nmr *3}`)
console.log(`${nmr} x 4 = ${nmr *4}`)
console.log(`${nmr} x 5 = ${nmr *5}`)
console.log(`${nmr} x 6 = ${nmr *6}`)
console.log(`${nmr} x 7 = ${nmr *7}`)
console.log(`${nmr} x 8 = ${nmr *8}`)
console.log(`${nmr} x 9 = ${nmr *9}`)
console.log(`${nmr} x 10 = ${nmr *10}`)